POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Example Name",
    "number": "123-4567-890"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "",
    "number": "123-4567-890"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Example Name 2"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "123-4567-890"
}